version: '3.3'
services:
  web-frontend:
    build: ./frontend
    ports:
      - 5000:80
    depends_on:
      - backend

  backend:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin: 
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8065:80
    environment:
      - PMA_ARBITARY=1
    depends_on:
      - backend

